language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: sme-springboot-webservice-deploy
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-unit-deployed: true
    on:
      repo: jaehoon-bang / spring-webservice
      branch: master

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - shake0824@smtown.com
