language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# S3 설정
before_deploy:
  - zip -r springboot-webservice *
  - mkdir -p deploy
  - mv springboot-webservice.zip deploy/springboot-webservice.zip
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY      # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY  # Travis repo settings에 설정된 값
    local-dir: deploy                   # before_deploy에서 생성한 디렉토리
    bucket: sme-springboot-webservice-deploy # 6-3-3에서 생성한 S3 버킷
    region: ap-northeast-1
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: jaehoon-bang/spring-webservice
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: sme-springboot-webservice-deploy
    key: springboot-webservice.zip
    bundle_type: zip
    application: spring-webservice
    deployment_group: springboot-webservice-group
    region: ap-northeast-1
    wait-until-deployed: true
    on:
      repo: jaehoon-bang/spring-webservice
      branch: master
# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - shake0824@smtown.com
